# Generated by Django 3.1.3 on 2021-10-13 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_comment_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_buyer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_comment', to='app1.product'),
        ),
    ]
