# Generated by Django 3.1.3 on 2021-10-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20211013_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Indore Madhya Pradesh ', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Indore ', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='Madhya Pradesh', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.CharField(max_length=100),
        ),
    ]
